const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "shirt",
      image: "/images/pl.webp",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      slug: "adidas-fit-pant",
      category: "pants",
      image: "/images/pl2.jpg",
      price: 65,
      countInStock: 5,
      brand: "puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Louis Vuitton",
      slug: "louis-vuitton-shirt",
      category: "shirt",
      image: "/images/pl3.webp",
      price: 25,
      countInStock: 10,
      brand: "Louis",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Christan Dior",
      slug: "christan-dior-pant",
      category: "pant",
      image: "/images/pl4.webp",
      price: 50,
      countInStock: 7,
      brand: "Dior",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
